# PyTorch for Deep Learning : Assignment 1

### All About torch.Tensor

PyTorch is a machine learning framework that is extremely popular for neural networks and deep learning models. A torch.Tensor is a multi-dimensional matrix containing elements of a single data type (PyTorch Documentation). The functions that I've picked from the torch package are as follows: 
- torch.zeros_like(input, dtype=None, layout=None, device=None, requires_grad=False, memory_format=torch.preserve_format)
- torch.abs(input, out=None)
- torch.where(condition, x, y) 
- torch.eye(n, m=None, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) 
- torch.arange(start=0, end, step=1, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) 

In [2]:
# Import torch and other required modules
import torch

## Function 1 - torch.zeros_like(input, dtype=None, layout=None, device=None, requires_grad=False, memory_format=torch.preserve_format

This function will return a tensor populated with  0, with the same size as input.

In [8]:
# Example 1 
first = torch.tensor([2,3,4.])
first.size()
second = torch.zeros_like(first)
second

tensor([0., 0., 0.])

In example 1, I created a tensor and then using the first tensor as the input, I created another tensor "second" of the same size. Also, since I did not specify the dtype in the function, it defaulted to the dtype of the input tensor.

In [18]:
# Example 2 - working
a = torch.tensor([4,5.])
a.size()
b = torch.zeros_like(a, dtype = torch.int64)
b

tensor([0, 0])

In this example, because I have specified the dtype to be integer, the newly created zero tensor doesn't default to the dtype of the input tensor.

In [25]:
# Example 3 - breaking (to illustrate when it breaks)
initial = torch.tensor([[1, 2], [3, 4]])
initial.size()
new = torch.zeros_like(initial, dtype = float32)

NameError: name 'float32' is not defined

The dtype should be torch.float32 and not only float32, hence it breaks.

This function can be used when we have an existing tensor and we want to create a new tensor with the same size filled with value 0.

## Function 2 - torch.abs(input, out=None)

This function returns the absolute value of every value in the input tensor.

In [3]:
# Example 1 - working
a = torch.tensor([-1, 5, -3, 6, -8])
torch.abs(a)


tensor([1, 5, 3, 6, 8])

The function returns an absolute value of all the elements in the tensor.

In [5]:
# Example 2 - working
a = torch.tensor([--1, 5, -(-3), 6, -8])
torch.abs(a)

tensor([1, 5, 3, 6, 8])

The function returns an absolute value of all the elements in the tensor.

In [18]:
# Example 3 - breaking (to illustrate when it breaks)
b = torch.tensor([1])
torch.abs(b, a)

TypeError: abs() takes 1 positional argument but 2 were given

The abs() function takes input as one tensor only, passing two tensors will break the function.

This function can be used when you want the absolute value / non-negative value of all your matrix elements.

## Function 3 - torch.where(condition, x, y)

This function essentially works like a traditional if-else condition. You need to pass two tensors to it "x" & "y" and specify a condition. It will return the tensor elements from either x or y depending on the condition specified. 

In [4]:
# Example 1 - working
x = torch.tensor([4,9,16,25])
y = torch.tensor([2,3,4,5])
z = torch.square(y)
torch.where(x == z, y, x)

tensor([2, 3, 4, 5])

In the above example, there are two tensors x & y, we check the condition , x equals square(y). If true, it returns the element of y, if not of x

In [16]:
# Example 2 - working
x = torch.tensor([4,10,16,26])
y = torch.tensor([2,3,4,5])
z = torch.square(y)

#checking if x equals square(y)

torch.where(x == z, y, x )

tensor([ 2, 10,  4, 26])

In this example, I'm again checking if x equals square(y). If true, it returns the number (y) as in the case of 2 & 4, else, it returns the element from x ( as in the case of 10 & 26).

In [17]:
# Example 3 - breaking (to illustrate when it breaks)

x = torch.tensor([4,10,16,26])
y = torch.tensor([2,3,4,5])
z = torch.square(y)

#creating tensors of torch.bool dtype

t = torch.tensor(1, dtype = torch.bool)
f = torch.tensor(0, dtype = torch.bool)

torch.where(x == z, t, f )

RuntimeError: "where_cpu" not implemented for 'Bool'

I tried to create boolean vectors that would output 1 or 0 for true or false, but where() is not implemented for 'Bool'

In [18]:
#Example 4

x = torch.tensor([4,10,16,26])
y = torch.tensor([2,3,4,5])
z = torch.square(y)

#creating tensors of torch.bool dtype

t = torch.tensor(1)
f = torch.tensor(0)

torch.where(x == z, t, f )

tensor([1, 0, 1, 0])

Here, I removed the torch.bool dtype and used them as integer tensors to output 1 for "true" and 0 for "False".

This function is very handy when you need to check a condition on tensors of same dimensions and accordingly output elements of either tensors based on the condition specified.

## Function 4 - torch.eye(n, m=None, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)

This eye() function is used to create a 2D identity matrix. (1s in the diagonal elements and 0 otherwise).

In [23]:
# Example 1 - working
torch.eye(4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In the above example, I created a 4x4 diagonal/identity matrix. I specified the number of rows, since I did not specify the columns, it defaulted to number of rows specified.

In [24]:
# Example 2 - working
torch.eye(3,2)

tensor([[1., 0.],
        [0., 1.],
        [0., 0.]])

In this example, I specified the rows and the columns.

In [33]:
# Example 3 - breaking (to illustrate when it breaks)

torch.eye(-5)

RuntimeError: n must be greater or equal to 0, got -5

The number of rows have to be positive.

This function can be used for linear algebra operations such an inverse matrix calculations.

## Function 5 - torch.arange(start=0, end, step=1, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)

This function outputs a tensor with values starting from the start and ending at the end argument. The difference between even value is based on the step argument. 

In [34]:
# Example 1 - working
torch.arange(5, 25 , 5)

tensor([ 5, 10, 15, 20])

In the above example, the start is 5, end is 25. The step is 5. We see that start is inclusive but end is not.

In [40]:
# Example 2 - working
torch.arange(0 ,50, 2)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
        36, 38, 40, 42, 44, 46, 48])

Start is 0, End is 50, step is 2.

In [43]:
# Example 3 - breaking (to illustrate when it breaks)

torch.arange(,6,1)

SyntaxError: invalid syntax (<ipython-input-43-dc4b25788441>, line 3)

The PyTorch documentation says the default value for "start" is 0. But, if we don't pass the value, the function breaks.

This function can be used to initialize/create a tensor with equally spaced values between a certain range. 

## Conclusion

So, after going through the PyTorch torch package documentation, I ended up selected functions such as zeros_like(), eye(), abs(), where() and arange() from the package. Functions such as torch.zeros_like(), torch.eye() and torch.arange() can be used to create and initialise a tensor. On the other hand, functions like torch.abs() and torch.where() require tensors as inputs and they output another tensor.

## Reference Links

* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html


In [20]:
!pip install jovian --upgrade --quiet

In [21]:
import jovian

In [22]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Please enter your API key ( from https://jovian.ml/ ):
API KEY: ········
[jovian] Updating notebook "mridul-chavan/01-tensor-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/mridul-chavan/01-tensor-operations


'https://jovian.ml/mridul-chavan/01-tensor-operations'